name: prepare-release

on:
  workflow_dispatch:
    inputs:
      versionIncrement:
        description: 'The version increment. Allowed values are "major", "minor" and "build".'
        required: true
        default: 'minor'     
jobs:
  prepare-release:
    runs-on: ubuntu-latest

    steps:
      - name: ☑ Validate arguments
        if: ${{ !contains(fromJson('["major","minor","build"]'), github.event.inputs.versionIncrement) }}
        run: |
          echo Unexpected versionIncrement specified. It be either "major", "minor" or "build". ${{ github.event.inputs.versionIncrement }} is not a valid value.
          exit 1
    
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure GIT
        run: |
          git config user.name "github-actions[bot]"
          git config user.email noreply@github.com
      
      - name: Nerdbank.GitVersioning
        uses: dotnet/nbgv@v0.4.0
          
      - run: nbgv prepare-release --versionIncrement ${{ github.event.inputs.versionIncrement }}
