name: prepare-release

on:
  workflow_dispatch:
    inputs:
      versionIncrement:
        description: 'The version increment. Allowed values are "major", "minor" and "build".'
        required: true
        default: 'minor'     
jobs:
  prepare-release:
    runs-on: ubuntu-latest

    steps:
      - name: 🧪 Validate arguments
        if: ${{ !contains(fromJson('["major","minor","build"]'), github.event.inputs.versionIncrement) }}
        run: |
          echo Unexpected versionIncrement specified. It be either "major", "minor" or "build". ${{ github.event.inputs.versionIncrement }} is not a valid value.
          exit 1
    
      - name: 🛒 Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ⚙️ Setup CI GIT
        run: |
          git config user.name "github-actions[bot]"
          git config user.email noreply@github.com
      
      - name: ⚙️ Setup GIT versioning
        uses: dotnet/nbgv@v0.4.0
          
      - name: 🛠️ Increment version on mainline + create release branch
        run: |
          nbgv prepare-release --versionIncrement ${{ github.event.inputs.versionIncrement }}
          echo "version=$NBGV_MajorMinorVersion" >> $GITHUB_ENV
        
#       - name: ⏩ Push updates to mainline
#         run: git push origin main
        
#       - name: ⏩ Push release branch to origin
#         run: git push origin release/v${{ version }}
