name: prepare-release
concurrency: 'prepare-release'

on:
  workflow_dispatch:
    inputs:
      versionIncrement:
        description: 'The version increment. Allowed values are "major" and "minor".'
        required: true
        default: 'minor'
        
jobs:  
  prepare-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && contains(fromJson('["major","minor"]'), github.event.inputs.versionIncrement)
    steps:   
      - name: 🛒 Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ⚙️ Setup CI GIT
        run: |
          git config user.name "github-actions[bot]"
          git config user.email noreply@github.com
      
      - name: ⚙️ Setup GIT versioning
        uses: dotnet/nbgv@v0.4.0
        with:
          setAllVars: true
          
      - name: 🛠️ Increment version.json on main + create release branch
        run: |
          nbgv prepare-release --versionIncrement ${{ github.event.inputs.versionIncrement }}
          git checkout release/v$NBGV_MajorMinorVersion
          
      - name: 🛠️ Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.2.1
        with:
          version: ${{ env.NBGV_MajorMinorVersion }}

      - name: 🛠️ Commit changelog to release branch
        id: make-commit
        run: |
          git add CHANGELOG.md
          git commit --message "Prepare ${{ github.event.inputs.versionIncrement }} release v${{ env.NBGV_MajorMinorVersion }}"

      - name: ⏩ Push version.json updates to main
        run: git push origin main
        
      - name: ⏩ Push release branch to origin
        run: git push origin release/v$NBGV_MajorMinorVersion

      - name: ⏭ Create pull request for release branch
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/v${{ env.NBGV_MajorMinorVersion }}
          base: ${{ github.ref }}
          title: Release of ${{ github.event.inputs.versionIncrement }} version v${{ env.NBGV_MajorMinorVersion }}
          reviewers: ${{ github.actor }} # By default, we request a review from the person who triggered the workflow.
          body: |
            Hi @${{ github.actor }}
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            Merging this PR will create a GitHub release, update the CHANGELOG.md file, and push new packages to NuGet.
            
            **NOTE:** Only small fixes are allowed to the release branch at this point. If you need to make minor or major changes, close the PR and make those
            changes to ${{ github.ref }} instead, and run the prepare-release workflow again once you are done.
